apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: analytics
      environment: test
  template:
    metadata:
      labels:
        service: analytics
        environment: test
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: analytics-service-container
          image: asia-south1-docker.pkg.dev/devops-sm/kubernetes-practice/analytics-service:v1.0.0
          env:  
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: REDIS_HOST
              value: "redis"
            - name: JAEGER_ENDPOINT
              value: "http://jaeger:4318/v1/traces"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
